variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

before_script:
  - docker info

build_containers:
  stage: build
  only:
    - master
    - ft/gitlab_ci
  script:
    - docker-compose build

push_to_registry:
  stage: deploy
  only:
    - master
  script:
    - docker push jukebox_web
    - docker push jukebox_files
    - docker push jukebox_frontend
    - docker push jukebox_backend
