variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

before_script:
  # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc//ci/ssh_keys/README.md
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

build_containers:
  stage: build
  only:
    - master
    - ft/gitlab_ci
  script:
    - docker-compose -f docker-compose.yml.dev build

push_to_registry:
  stage: deploy
  only:
    - master
  script:
    - docker push jukebox_web
    - docker push jukebox_files
    - docker push jukebox_frontend
    - docker push jukebox_backend
