#!/bin/sh
export CI_REGISTRY=example.com:5000
export JUKEBOX_SSL_CERT=./ssl/ssl.crt
export JUKEBOX_SSL_KEY=./ssl/ssl.key
export JUKEBOX_PORT=443
export JUKEBOX_DATA=./data
export JUKEBOX_MUSIC_PATH=./music
export JUKEBOX_LOG=./logs

# first make a backup
./backup.sh

docker-compose -f docker-compose.yml.deploy $@
